name: OneDrive

services:
  onedrive:
    image: driveone/onedrive:${VERSION}-debian
    container_name: onedrive
    volumes:
      - onedrive_conf:/onedrive/conf
      - ~/OneDrive:/onedrive/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+-debian$$
      - traefik.enable=false

volumes:
  onedrive_conf:
    name: onedrive_conf
    external: true
