name: OneDrive

services:
  onedrive:
    image: driveone/onedrive:2.5.5-debian
    volumes:
      - onedrive_conf:/onedrive/conf
      - ~/OneDrive:/onedrive/data
    restart: unless-stopped

volumes:
  onedrive_conf:
    external: true
