version: "3.4"

services:
  onedrive:
    image: driveone/onedrive:stretch-v2.4.1
    restart: unless-stopped
    volumes:
      - onedrive_conf:/onedrive/conf
      - ~/OneDrive:/onedrive/data

volumes:
  onedrive_conf:
    external: true
